hubmapconsortium/ccf-ui

src/app/components/dataview/dataview.component.spec.ts
src/app/components/leftbar/leftbar.component.spec.ts
src/app/components/leftbar/leftbar.component.ts
src/app/components/toolbar/toolbar.component.spec.ts
src/app/views/main/main.component.spec.ts

Pbi 29 ui scaffolding

---

src/app/components/tissues-browser-grid-popover-content/tissues-browser-grid-popover-content.component.html
src/app/components/tissues-browser-grid-popover-content/tissues-browser-grid-popover-content.component.scss
src/app/components/tissues-browser-grid/tissues-browser-grid.component.scss
src/app/views/home/home.component.scss
src/styles.scss

The size of the popover is currently based on its contents (with min/max sizes set of course). This has to be fixed in a future issue.

Pbi 18 popover styling

---

sonar-project.properties

Trying to fix the coverage in sonar cloud. (WIP)

---

.travis.yml

Fixing SONAR cloud test coverage issue.

---

src/app/shared/services/tissue-data/tissue-data.service.ts
src/app/views/tissue/tissue.component.ts

Fixed flickering when switching to a new tissue

---

src/app/components/leftbar/leftbar.component.html
src/app/components/leftbar/leftbar.component.scss

Issue - #13 
Added a link to the feedback form in the comment icon

Added link to feedback form

---

src/app/shared/services/body-data/body-data.service.ts
src/app/shared/services/organ-data/organ-data.service.ts

Pbi 50 image embedding absolute path

---

src/app/app-state.module.ts
src/app/shared/state/search/search.action.ts
src/app/shared/state/search/search.model.ts
src/app/shared/state/search/search.state.ts

Issue - #23, #15, #14
Search state setup
@bherr2

search state setup

---

src/app/components/sidenav/sidenav.component.html
src/app/components/sidenav/sidenav.component.spec.ts
src/app/shared/resolvers/tissue-resolver/tissue-resolver.service.spec.ts
src/app/shared/services/search/search.service.spec.ts
src/app/shared/services/search/search.service.ts
src/app/shared/state/navigation/navigation.state.spec.ts
src/app/shared/state/navigation/navigation.state.ts
src/app/shared/state/search/search.action.ts
src/app/shared/state/search/search.model.ts
src/app/shared/state/search/search.state.spec.ts
src/app/shared/state/search/search.state.ts

Issue - #18 
Added utility for building filter functions.
Connected the tissues browser data to the search state.

Pbi 18 tissue search filter

---

src/app/app-state.module.ts
src/app/components/gender-selector/gender-selector.component.html
src/app/components/gender-selector/gender-selector.component.scss
src/app/components/gender-selector/gender-selector.component.spec.ts
src/app/components/gender-selector/gender-selector.component.ts
src/app/components/gender-selector/gender-selector.module.ts
src/app/components/header/header.component.ts
src/app/components/navigation/navigation.component.ts
src/app/components/search/search.component.html
src/app/components/search/search.component.scss
src/app/components/search/search.component.ts
src/app/components/search/search.module.ts
src/app/shared/services/search/search.service.spec.ts
src/app/shared/services/search/search.service.ts
src/app/shared/state/icon-registry/icon-registry.action.ts
src/app/shared/state/search/search.action.ts
src/app/views/home/home.component.ts

Issue - #15 
Added component for selecting a gender to be filtered on.

Pbi 15 gender selection

---

src/app/components/tissues-browser-grid/tissues-browser-grid.component.scss
src/app/shared/services/navigation/navigation.service.spec.ts
src/app/shared/services/navigation/navigation.service.ts
src/app/shared/services/search/search.service.spec.ts
src/app/shared/services/search/search.service.ts
src/app/views/main/main.component.html
src/app/views/main/main.component.scss
src/app/views/main/main.component.ts

Issue - #19 
Added a search criteria description to the top right of the main view.

Pbi 19 search critera display

---

src/app/shared/services/search/search.service.spec.ts
src/app/shared/services/search/search.service.ts

Description of changes -  Added missing test-cases and documentation for search service.
@bherr2 

Pbi 23 filter tissues by technology and tmc

---

src/app/shared/state/database/database.models.ts
src/app/shared/state/navigation/navigation.state.spec.ts
src/app/views/body/body.component.html
src/app/views/body/body.component.scss
src/app/views/organ/organ.component.html
src/app/views/organ/organ.component.scss

Size fixes for organ

---

src/app/components/age-selector/age-selector.component.html
src/app/components/age-selector/age-selector.component.scss
src/app/components/age-selector/age-selector.component.ts
src/app/components/age-selector/age-selector.module.ts
src/app/components/gender-selector/gender-selector.component.html
src/app/components/search/search.component.html
src/app/components/search/search.component.scss
src/app/shared/services/search/search.service.ts
src/styles/global/_sizes.scss

Search area prettify

---

src/app/components/callout/callout.component.html
src/app/components/callout/callout.component.scss
src/app/components/callout/callout.component.spec.ts
src/app/components/callout/callout.component.ts
src/app/components/callout/callout.module.ts
src/app/shared/services/organ-data/organ-data.service.spec.ts
src/app/shared/services/organ-data/organ-data.service.ts
src/app/shared/state/search/search.state.ts
src/app/views/organ/organ.component.html
src/app/views/organ/organ.component.scss
src/app/views/organ/organ.component.spec.ts
src/app/views/organ/organ.component.ts
src/app/views/organ/organ.module.ts

Issue - #17 
Cleaned up organ component and service to fix memory leaks and incorrect handling of async actions.
Created a callout component.

Organ fixes

---

src/app/shared/services/body-data/body-data.service.spec.ts
src/app/views/body/body.component.spec.ts

Pbi 87 unit tests for body

---

package-lock.json
src/app/components/tissues-browser-grid-popover-content/tissues-browser-grid-popover-content.component.html
src/app/components/tissues-browser-grid-popover-content/tissues-browser-grid-popover-content.component.spec.ts
src/app/components/tissues-browser-grid-popover-content/tissues-browser-grid-popover-content.component.ts
src/app/views/main/main.component.html
src/app/views/main/main.component.scss
src/app/views/main/main.module.ts

Pbi 20 downloadbutton

---

src/app/shared/state/ontology/ontology.model.ts
src/app/shared/state/ontology/ontology.state.spec.ts
src/app/shared/state/ontology/ontology.state.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Issues - #25 and #26 
@bherr2 

added functionality for fetching and parsing ontology

---

package-lock.json
src/app/components/age-selector/age-selector.component.html
src/app/components/age-selector/age-selector.component.ts
src/app/shared/services/search/search.service.ts

Issue - #97 
TO-DO checklist before submitting your pull-request - 
- [ x ] Are all acceptance criteria met ? 
- [ x ] Has the code been documented properly ?
- [ x ] Does component css-class structure conform to the Blue Dino style template i.e. top-level element .wrapper, .container and other inside css classes ?
- [ x ] Have all checks passed ?
- [ x ] Have you tested inter-browser functionality (should work on the latest Chrome, Firefox and Edge browsers) ?

Pbi 89 minmaxslider

---

src/app/components/ontology-tree/ontology-tree.component.html
src/app/components/ontology-tree/ontology-tree.component.scss
src/app/components/ontology-tree/ontology-tree.module.ts
src/app/shared/state/ontology/ontology.state.ts
src/app/views/main/main.component.spec.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Pbi 25 tree tweaks

---

src/app/components/age-selector/age-selector.component.html
src/app/components/age-selector/age-selector.component.ts
src/app/shared/services/search/search.service.ts

Fixed age range selection bugs

---

src/app/shared/services/body-data/body-data.service.ts
src/app/views/body/body.component.html
src/app/views/body/body.component.spec.ts
src/app/views/body/body.component.ts
src/app/views/organ/organ.component.html
src/app/views/organ/organ.component.ts

Issue - #90 
added count check inside interpolation of body and organ.
@axdanbol 
@bherr2 

added singulars for just 1 record

---

src/app/components/search-categories/search-categories.component.html
src/app/components/search-categories/search-categories.component.spec.ts
src/app/components/search-categories/search-categories.component.ts
src/app/components/search/search.component.ts

Issue - #92 
removed TMC prefixes
@axdanbol 
@bherr2 
@GagsdName 

removed tmc prefixes

---

src/app/shared/services/body-data/body-data.service.spec.ts

few more tests.

---

src/app/shared/services/body-data/body-data.service.spec.ts

Unit tests

---

.travis.yml
src/app/components/search-categories/search-categories.component.html
src/app/components/search-categories/search-categories.component.ts
src/app/components/search-categories/search-categories.module.ts
src/app/components/search/search.component.ts

Tooltip for tech

---

src/app/components/search/search.component.ts
src/app/shared/services/navigation/navigation.service.spec.ts
src/app/shared/services/navigation/navigation.service.ts
src/app/shared/state/navigation/navigation.state.ts
src/app/shared/state/ontology/ontology.state.spec.ts
src/app/shared/state/ontology/ontology.state.ts

Fix routing

---

src/app/components/ontology-search/ontology-search.component.scss
src/app/components/search/search.component.html
src/app/components/tissues-browser-grid-popover-content/tissues-browser-grid-popover-content.component.html
src/app/components/tissues-browser-grid-popover-content/tissues-browser-grid-popover-content.component.scss
src/app/views/main/main.component.scss
src/app/views/tissue/tissue.component.scss
src/styles/global/_colors.scss

PBI- 7 Changed download icon color
PBI - 10 Changed the background color for the search
PBI - 6 Moved the Technologes filter above ontology.

PBI-5 Addional styles for details button

---

src/app/shared/components/dropdown/dropdown.component.html
src/app/shared/components/dropdown/dropdown.component.scss
src/app/shared/components/dropdown/dropdown.component.ts
src/app/shared/components/dual-slider/dual-slider.component.html
src/app/shared/components/dual-slider/dual-slider.component.scss
src/app/shared/components/dual-slider/dual-slider.component.ts

Description of changes - Added styling and animations, fixed bugs with slider input

Dual slider

---

.gitignore
src/app/app.component.html
src/app/app.component.ts
src/app/modules/filters/filters-popover/filters-popover.component.ts
src/app/shared/components/checkbox/checkbox.component.scss
src/app/shared/components/drawer/drawer/drawer.component.ts
src/app/shared/components/dropdown/dropdown.component.scss
src/app/shared/components/dual-slider/dual-slider.component.scss
src/app/shared/components/dual-slider/dual-slider.component.ts

Misc stories 3-17

---

.gitignore
src/app/modules/filters/filters-popover/filters-popover.component.html
src/app/modules/filters/filters-popover/filters-popover.component.scss
src/app/modules/filters/filters-popover/filters-popover.component.ts

PBI 143 filter animation

---

src/app/modules/filters/filters-popover/filters-popover.component.scss

Filter popover opacity fix

---

karma.conf.js
sonar-project.properties
src/app/core/header/header.component.html
src/app/core/header/header.component.spec.ts
src/app/modules/info/info-button/info-button.component.spec.ts
src/app/modules/info/info-button/info-button.component.ts

Documentation and testing

---

src/app/shared/components/dropdown/dropdown.component.spec.ts

Tests for dropdown component

---

src/app/modules/filters/filters-content/filters-content.component.html
src/app/shared/components/checkbox/checkbox.component.spec.ts
src/app/shared/components/checkbox/checkbox.component.ts

testing to 100% for checkbox component

---

src/app/modules/filters/filters-content/filters-content.component.html
src/app/modules/filters/filters-content/filters-content.component.spec.ts
src/app/modules/filters/filters-content/filters-content.component.ts

tests + documentation for filters-content

---

src/app/modules/filters/filters-popover/filters-popover.component.spec.ts
src/app/modules/filters/filters-popover/filters-popover.component.ts

testing / documentation of filters-popover

---

src/app/modules/info/info-dialog/info-dialog.component.spec.ts
src/app/modules/info/info-dialog/info-dialog.component.ts

Test document info dialog

---

src/app/core/header/header.component.html
src/app/core/header/header.component.spec.ts
src/app/core/header/header.component.ts
src/app/core/header/header.module.ts

Testing header

---

src/app/shared/components/checkbox/checkbox.component.ts

documentation for the checkbox component

---

src/app/modules/info/info-button/info-button.component.spec.ts

Testing info button

---

src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts

Description of changes - Adding tests and documentation to the app.component.ts file.

test + document the app.component

---

src/app/shared/components/dual-slider/dual-slider.component.html
src/app/shared/components/dual-slider/dual-slider.component.spec.ts
src/app/shared/components/dual-slider/dual-slider.component.ts

Testing dual slider

---

src/app/modules/ontology-exploration/ontology-selection/ontology-selection.component.spec.ts
src/app/modules/ontology-exploration/ontology-selection/ontology-selection.component.ts
src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.spec.ts
src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.ts

Ontology tree tests

---

src/app/app.component.html
src/app/app.module.ts
src/app/modules/filters/filters-popover/filters-popover.component.html
src/app/modules/filters/filters-popover/filters-popover.component.scss
src/app/modules/filters/filters-popover/filters-popover.component.ts
src/app/shared/components/drawer/drawer/drawer.component.ts

Filters popover fix

---

src/app/core/models/flat-node.ts
src/app/core/services/ontology-search/ontology-search.service.ts
src/app/core/services/theming/theming.module.ts
src/app/core/services/theming/theming.service.ts
src/app/core/store/icon-registry/default-icons.ts
src/app/core/store/icon-registry/icon-registry.state.ts
src/app/core/store/ontology/ontology.state.ts
src/app/core/store/search/search.state.ts
src/app/core/store/store.module.ts
src/app/shared/components/drawer/container/container.component.ts
src/app/shared/components/drawer/content/content.component.ts
src/app/shared/components/drawer/drawer/drawer.component.ts
src/app/shared/components/drawer/messages.ts
src/app/shared/components/drawer/toggle-button/toggle-button.component.ts
src/app/shared/services/message/message.service.ts

Added a lot of code documentation.

Added almost all missing code documentation

---

.gitattributes
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/modules/filters/filters-content/filters-content.component.ts
src/app/modules/filters/filters-popover/filters-popover.component.ts
src/app/modules/image-viewer/image-viewer-content/image-viewer-content.component.html
src/app/modules/image-viewer/image-viewer-content/image-viewer-content.component.scss
src/app/modules/image-viewer/image-viewer-content/image-viewer-content.component.spec.ts
src/app/modules/image-viewer/image-viewer-content/image-viewer-content.component.ts
src/app/modules/image-viewer/image-viewer-content/image-viewer-content.module.ts
src/app/modules/image-viewer/image-viewer-popover/image-viewer-popover.component.html
src/app/modules/image-viewer/image-viewer-popover/image-viewer-popover.component.spec.ts
src/app/modules/image-viewer/image-viewer-popover/image-viewer-popover.component.ts
src/app/shared/components/accordion/accordion.component.html
src/app/shared/components/accordion/accordion.component.scss
src/app/shared/components/accordion/accordion.component.ts
src/app/shared/components/accordion/accordion.module.ts

Accordion4

---

src/app/modules/results-browser/results-browser-item/results-browser-item.component.html
src/app/modules/results-browser/results-browser-item/results-browser-item.component.scss
src/app/modules/results-browser/results-browser/results-browser.component.html
src/app/modules/results-browser/results-browser/results-browser.component.spec.ts

Pbi 144 tissue browser

---

src/app/app.component.html
src/app/modules/results-browser/results-browser/results-browser.component.html
src/app/modules/results-browser/results-browser/results-browser.component.scss
src/app/modules/results-browser/results-browser/results-browser.component.spec.ts
src/app/modules/results-browser/results-browser/results-browser.component.theme.scss
src/app/modules/results-browser/results-browser/results-browser.component.ts
src/themes/common/_theming.scss

gradient added, tested, documented

---

package.json
projects/ccf-body-ui/src/lib/body-ui-layer.ts
projects/ccf-body-ui/src/lib/body-ui.ts
projects/ccf-database/src/lib/ccf-database.ts
projects/ccf-database/src/lib/ccf-spatial-scene.ts
projects/ccf-database/src/lib/queries/aggregate-results-n3.ts
projects/ccf-database/src/lib/queries/find-ids-n3.ts
projects/ccf-database/src/lib/util/hubmap-data.ts
projects/ccf-database/src/lib/util/patches/hubmap-rui-locations-only-patch.ts
projects/ccf-database/src/lib/util/patches/hubmap-share-donor-instances-patch.ts
projects/ccf-database/src/lib/util/patches/hubmap-vu-patch.ts
projects/ccf-database/src/lib/util/patches/index.ts
projects/ccf-database/src/lib/util/prefixes.ts
projects/ccf-database/src/process-hubmap-data.ts
projects/ccf-database/tsconfig.cli.json
projects/triple-store-utils/src/lib/triple-store-utils.spec.ts
projects/triple-store-utils/src/lib/triple-store-utils.ts
src/environments/environment.ts

* Added offline script to convert HuBMAP search-api response to CCF JSON-LD
* Added option to load the JSON-LD vs original HuBMAP search-api response
* Some Body UI updates for presentation
* Added more aggregate results (needs a browser list update)
* Loaded new metadata from the hubmap response and fully added BMI filtering
* Limited data to subtrees of the provenance graph that include a rui_location
* Made triple-store-utils.addXToStore functions operate more similarly, being able to accept the raw data or a url.

Data Processing Improvements

---

src/app/modules/results-browser/results-browser/results-browser.component.scss

style fix to make browser stat box more dynamic

---

src/app/modules/color-scheme/color-bar/color-bar.component.spec.ts
src/app/modules/color-scheme/color-scheme-contents/color-scheme-contents.component.spec.ts
src/app/modules/color-scheme/color-scheme-popup/color-scheme-popup.component.spec.ts
src/app/modules/image-viewer/color-picker-launcher/color-picker-launcher.component.spec.ts
src/app/modules/image-viewer/image-viewer-layers/image-viewer-layers.component.spec.ts

tests for the files I reworked

---

src/app/modules/color-scheme/color-scheme-popup/color-scheme-popup.component.spec.ts
src/app/modules/image-viewer/image-viewer-accordion/image-viewer-accordion.component.scss

Color selector fixes

---

src/app/modules/image-viewer/image-viewer-layers/image-viewer-layers.component.spec.ts
src/app/modules/image-viewer/image-viewer-legend/image-viewer-legend.component.scss
src/app/modules/image-viewer/image-viewer-legend/image-viewer-legend.component.spec.ts
src/app/modules/image-viewer/image-viewer-popover/image-viewer-popover.component.spec.ts

tests, css change

---

src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/core/store/data/data.state.ts
src/app/modules/ontology-exploration/ontology-exploration.theme.scss
src/app/modules/ontology-exploration/ontology-selection/ontology-selection.component.html
src/app/modules/ontology-exploration/ontology-selection/ontology-selection.component.ts
src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.html
src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.ts

Pbi 169 ontology

---

src/app/core/header/header.component.ts
src/app/core/models/image-viewer-layer.ts
src/app/modules/color-scheme/color-picker-launcher/color-picker-launcher.component.html
src/app/modules/color-scheme/color-scheme-contents/color-scheme-contents.component.html
src/app/modules/color-scheme/color-scheme-contents/color-scheme-contents.component.scss
src/app/modules/color-scheme/color-scheme-contents/color-scheme-contents.component.ts
src/app/modules/color-scheme/color-scheme-popup/color-scheme-popup.component.html
src/app/modules/color-scheme/color-scheme-popup/color-scheme-popup.component.spec.ts
src/app/modules/color-scheme/color-scheme-popup/color-scheme-popup.component.ts
src/app/modules/image-viewer/image-viewer-popover/image-viewer-popover.component.ts
src/app/modules/image-viewer/image-viewer.theme.scss
src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.theme.scss
src/app/modules/results-browser/results-browser-item/results-browser-item.component.theme.scss
src/app/modules/results-browser/results-browser/results-browser.component.theme.scss
src/app/shared/components/drawer/drawer.theme.scss
src/themes/_dark.scss
src/themes/_light.scss

Pre release fixes

---

src/app/modules/color-scheme/color-scheme-contents/color-scheme-contents.component.ts
src/app/modules/image-viewer/image-viewer-layers/image-viewer-layers.component.html
src/app/modules/image-viewer/image-viewer-layers/image-viewer-layers.component.scss

- Added text description to layers panel if the image is rgb
- Added throttle to brightness changes for somewhat smoother image viewer updates

Image viewer tweaks and fixes

---

src/app/modules/image-viewer/image-viewer-accordion/image-viewer-accordion.component.html
src/app/modules/image-viewer/image-viewer-accordion/image-viewer-accordion.component.ts
src/app/modules/image-viewer/image-viewer-content/image-viewer-content.component.html
src/app/modules/image-viewer/image-viewer-content/image-viewer-content.component.ts
src/app/modules/image-viewer/image-viewer-layers/image-viewer-layers.component.html
src/app/modules/image-viewer/image-viewer-layers/image-viewer-layers.component.ts
src/app/modules/image-viewer/image-viewer-popover/image-viewer-popover.component.html
src/app/modules/image-viewer/image-viewer-popover/image-viewer-popover.component.ts
src/app/modules/results-browser/results-browser/results-browser.component.html
src/app/modules/results-browser/results-browser/results-browser.component.scss
src/app/modules/results-browser/results-browser/results-browser.component.spec.ts
src/app/modules/results-browser/results-browser/results-browser.component.ts

- Fixed strange scroll behavior in the results browser
- Fixed outdated information being displayed in the layers panel in the image viewer

More image viewer tweaks and fixes

---

projects/ccf-rui/src/app/core/store/page/page.state.ts
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.html
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.scss
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.ts
projects/ccf-rui/src/app/shared/components/labeled-slide-toggle/labeled-slide-toggle.component.html
projects/ccf-rui/src/app/shared/components/labeled-slide-toggle/labeled-slide-toggle.component.ts
projects/ccf-rui/src/app/shared/components/name-input/name-input.component.html
projects/ccf-rui/src/app/shared/components/name-input/name-input.component.spec.ts
projects/ccf-rui/src/app/shared/components/name-input/name-input.component.ts

- Fixed some styling errors
- Fixed output bug in labeled-slide-toggle
- Connected name inputs to state
- Exposed `setEmbedded(true|false, [url])` on the global window in development mode

General code cleanup with styling and bug fixes

---

projects/ccf-rui/src/app/modules/content/content.component.theme.scss
projects/ccf-rui/src/app/modules/info/info-button/info-button.component.ts
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.component.theme.scss
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.theme.scss
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.theme.scss
projects/ccf-rui/src/styles.scss

Added custom class for darker modal overlays. #315

Pbi 315 modal overlay color

---

projects/ccf-rui/src/app/modules/content/content.component.theme.scss
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.component.theme.scss
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.theme.scss
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.theme.scss

Added hover states for the reset buttons. #318

Pbi 318 reset btn hovers

---

projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.scss

Style changes for active organ in the organ selector:  font size 16px, font weight bold. #310

css changes for active organ.

---

projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.scss
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.theme.scss

Updated stage nav styling so that the components wrap better, and added hover state for the radios.
Issue #314

pbi 314 updated stage navbar styling.

---

projects/ccf-rui/src/app/shared/components/name-input/name-input.component.scss

Changed first and last name inputs to left aligned. Issue #319

profile text to left align.

---

projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.html
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.scss
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.theme.scss
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.module.ts
projects/ccf-rui/src/themes/_light.scss
projects/ccf-rui/src/themes/common/_theming.scss

Changed out the input sliders for angular material slider components. Updated styling.
Issue #317

changed out the slider inputs for angular material sliders.

---

projects/ccf-eui/src/app/core/header/header.component.scss
projects/ccf-eui/src/app/modules/color-scheme/color-bar/color-bar.component.scss
projects/ccf-eui/src/app/modules/color-scheme/color-scheme-contents/color-scheme-contents.component.scss
projects/ccf-eui/src/app/modules/filters/filters-content/filters-content.component.scss
projects/ccf-eui/src/app/modules/image-viewer/image-viewer-legend/image-viewer-legend.component.scss
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-search/ontology-search.component.scss
projects/ccf-eui/src/app/shared/components/drawer/toggle-button/toggle-button.component.scss
projects/ccf-eui/src/app/shared/components/dropdown/dropdown.component.scss
projects/ccf-eui/src/app/shared/components/dual-slider/dual-slider.component.scss
projects/ccf-eui/src/styles.scss
projects/ccf-eui/src/themes/common/_typography.scss
projects/ccf-rui/src/app/shared/components/drawer/toggle-button/toggle-button.component.scss
projects/ccf-rui/src/app/shared/components/opacity-slider/opacity-slider.component.scss
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.scss
projects/ccf-rui/src/app/shared/components/visibility-toggle/visibility-toggle.component.scss
projects/ccf-rui/src/styles.scss
projects/ccf-rui/src/themes/common/_typography.scss

Convert px to rem

---

projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.ts

Fix opacity bug

---

projects/ccf-rui/src/app/modules/content/content.component.scss
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.scss
projects/ccf-rui/src/app/modules/header/header.component.html
projects/ccf-rui/src/app/modules/header/header.component.scss
projects/ccf-rui/src/app/modules/info/info-button/info-button.component.scss
projects/ccf-rui/src/app/shared/components/opacity-slider/opacity-slider.component.scss
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.scss
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.scss
projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.ts

Pbi 348 styling updates

---

projects/ccf-rui/src/app/core/models/visibility-item.ts
projects/ccf-rui/src/app/core/store/model/model.state.spec.ts
projects/ccf-rui/src/app/core/store/model/model.state.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.scss
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.spec.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.theme.scss
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.ts
projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.ts

Pretty much ready except the extraction sites that are currently in the app don't have the tooltip field populated.  If someone can point me to where they are I'll add them in. 
Issue #346

Pbi 346 extraction site tooltip

---

projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.scss
projects/ccf-rui/src/app/shared/components/visibility-toggle/visibility-toggle.component.scss

Fix for eye icon position

---

projects/ccf-rui/src/app/core/store/model/model.state.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/shared/components/extraction-set-dropdown/extraction-set-dropdown.component.html
projects/ccf-rui/src/app/shared/components/extraction-set-dropdown/extraction-set-dropdown.component.spec.ts
projects/ccf-rui/src/app/shared/components/extraction-set-dropdown/extraction-set-dropdown.component.ts

Add extraction sets with tooltips to state

---

projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.html
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.scss
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.spec.ts
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.ts

Pbi 354 hold to scroll carousel

---

projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.scss

Increase tick size

---

projects/ccf-rui/src/app/core/store/model/model.state.spec.ts
projects/ccf-rui/src/app/core/store/model/model.state.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.spec.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.ts
projects/ccf-rui/src/app/shared/components/visibility-toggle/visibility-toggle.component.html

added functionality for changing opacities to 20% and back

---

projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.ts

Disable opacity slider when no visible item selected

---

projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.scss

Fix indentation in expansion panels

---

projects/ccf-rui/src/app/core/store/model/model.state.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.spec.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.ts

Pbi 375 extraction sites fix

---

projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.ts
projects/ccf-rui/src/app/shared/components/labeled-slide-toggle/labeled-slide-toggle.component.html
projects/ccf-rui/src/app/shared/components/labeled-slide-toggle/labeled-slide-toggle.component.scss
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.ts

Disable L/R slider when not applicable

---

projects/ccf-rui/src/app/modules/header/header.component.scss

Change header height

---

projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.html
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.scss
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.theme.scss
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.module.ts

Minor styling improvements to stage nav dropdown

Add fade in-out effect, convert hr to mat-divider

---

projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.ts

Stop stage nav from disappearing when not in dropdown mode

---

CHANGELOG.md
projects/ccf-database/src/lib/hubmap/hubmap-data.ts
projects/ccf-database/src/lib/interfaces.ts
projects/ccf-database/src/lib/queries/find-ids-n3.ts
projects/ccf-rui/src/app/core/store/model/model.state.spec.ts
projects/ccf-rui/src/app/core/store/model/model.state.ts
projects/ccf-rui/src/app/core/store/registration/registration.state.spec.ts
projects/ccf-rui/src/app/core/store/registration/registration.state.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.spec.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.ts
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.html
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.spec.ts
projects/ccf-rui/src/app/shared/components/organ-selector/organ-selector.component.ts

Updated references of 'gender' to 'sex'. #406 
Updated the ogran-carousel component, and the model state to allow the organ-carousel to update selection when the state changes. #407

Pbi 407 organ carousel state

---

package-lock.json
projects/ccf-rui/src/app/core/store/model/model.state.ts
projects/ccf-rui/src/app/modules/content/content.component.html
projects/ccf-rui/src/app/modules/content/content.component.scss
projects/ccf-rui/src/app/modules/content/content.component.spec.ts
projects/ccf-rui/src/app/modules/content/content.component.ts
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.html
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.scss
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.spec.ts
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.ts
projects/ccf-rui/src/app/modules/info/info-dialog/info-dialog.component.spec.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.scss
projects/ccf-rui/src/app/modules/review/review-modal/review-modal.component.spec.ts
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.scss
projects/ccf-rui/src/styles.scss

Fixes #377
Scrollbar rail/track visibility for the sidebars has not been fixed. Trying to add resize detection to the sidebars interferes with the tooltip element and will require further investigation on possible fixes.

Pbi 377 scrollbar style v2

---

package-lock.json
package.json
projects/ccf-eui/src/app/modules/image-viewer/image-viewer-layers/image-viewer-layers.component.scss
projects/ccf-image-viewer/src/lib/image-viewer.ts
tsconfig.base.json

Pbi 300 layers section

---

projects/ccf-eui/src/app/core/store/data/data.state.ts

This makes one less query to the search api
Part of #296

Reused query results for term occurences in the common case

---

projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html

Pbi 444 - left sidebar organization

---

projects/ccf-rui/src/app/modules/content/video-modal/video-modal-launcher/video-modal-launcher.component.html
projects/ccf-rui/src/app/modules/content/video-modal/video-modal-launcher/video-modal-launcher.component.scss
projects/ccf-rui/src/app/modules/content/video-modal/video-modal/video-modal.component.html
projects/ccf-rui/src/app/modules/content/video-modal/video-modal/video-modal.component.scss
projects/ccf-rui/src/app/modules/content/video-modal/video-modal/video-modal.component.theme.scss

video modal styles changed

---

projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.html
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.module.ts
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.scss
projects/ccf-rui/src/app/modules/review/review-button/review-button.component.html
projects/ccf-rui/src/app/modules/review/review-button/review-button.module.ts
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.component.html
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.module.ts
projects/ccf-rui/src/app/shared/components/name-input/name-input.component.html
projects/ccf-rui/src/app/shared/components/name-input/name-input.module.ts
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.html
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.module.ts

added more tooltips. waiting on word from Leonard.  Wanted to make sure he wants to go against material design before spending time altering tooltips.

Pbi 451 tooltips

---

projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.html
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.ts

Convert 3d/register toggle to radio button

Register 3d toggle

---

projects/ccf-rui/src/app/core/store/reference-data/reference-data.state.ts
projects/ccf-rui/src/app/core/store/registration/registration.state.spec.ts
projects/ccf-rui/src/app/core/store/registration/registration.state.ts

Set organ on `RegistrationState:editRegistration`

---

projects/ccf-rui/src/app/app.component.html
projects/ccf-rui/src/app/app.component.scss

So I think this is some sort of hack by manipulating the height.
In the previous code, the div was being translated (moved up) which is why the stage div was also being translated - hence the big chin at the bottom. This doesn't look as elegant as the previous one, but let me know if this works as of now.

pbi 490 updated collapsing of carousel

---

projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/core/header/header.component.spec.ts

While working on the EUI styles I had commented the spinner so that I could see the UI changes quicker. I had forgotten to uncomment it. This PR is to remove all the code smells from my previous commit into the EUI.

pbi removed code smell

---

projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/core/header/header.component.spec.ts
projects/ccf-rui/src/app/app.component.scss
projects/ccf-rui/src/app/core/store/scene/scene.state.ts
projects/ccf-rui/src/app/modules/content/video-modal/video-modal-launcher/video-modal-launcher.component.theme.scss
projects/ccf-rui/src/app/shared/components/drawer/drawer.theme.scss
projects/ccf-rui/src/app/shared/components/drawer/toggle-button/toggle-button.component.scss
projects/ccf-rui/src/styles.scss
projects/ccf-rui/src/themes/_light.scss
projects/ccf-shared/src/lib/components/info/info-button/info-button.component.html
projects/ccf-shared/src/lib/components/info/info-button/info-button.component.scss
projects/ccf-shared/src/lib/components/info/info-button/info-button.component.theme.scss
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.scss
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.theme.scss
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts

Target Issues #519 
Still working on
- Removing the yellow cube when no organ is selected
- Hover state of the play button of the video (I have asked Leonard how it should be)

RUI QA fixes

---

projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.scss
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.theme.scss
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.scss
projects/ccf-rui/src/app/shared/components/labeled-slide-toggle/labeled-slide-toggle.component.theme.scss
projects/ccf-rui/src/app/shared/components/opacity-slider/opacity-slider.component.scss
projects/ccf-rui/src/app/shared/components/opacity-slider/opacity-slider.component.theme.scss
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.html
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.module.ts
projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.html
projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.scss
projects/ccf-rui/src/app/shared/components/visibility-toggle/visibility-toggle.component.html
projects/ccf-rui/src/app/shared/components/visibility-toggle/visibility-toggle.component.scss
projects/ccf-rui/src/app/shared/components/visibility-toggle/visibility-toggle.component.theme.scss
projects/ccf-rui/src/themes/_light.scss

Pbi RUI QA fixes

---

projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.html
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.scss
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.theme.scss
projects/ccf-rui/src/app/modules/review/review-button/review-button.component.html
projects/ccf-rui/src/app/modules/review/review-button/review-button.component.spec.ts
projects/ccf-rui/src/app/modules/review/review-button/review-button.component.ts
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.scss
projects/ccf-rui/src/app/shared/components/tag-search/tag-search.component.html
projects/ccf-rui/src/app/shared/components/tag-search/tag-search.component.scss
projects/ccf-rui/src/app/shared/components/tag-search/tag-search.component.theme.scss
projects/ccf-rui/src/themes/_dark.scss

Please let me know if this is the right way to do it. The button is disabled till the FN and LN are filled and an organ is selected.

Fixed review and download button

---

projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/app.component.scss
projects/ccf-eui/src/app/app.module.ts
projects/ccf-eui/src/styles.scss
projects/ccf-eui/src/themes/common/_theming.scss
projects/ccf-rui/src/styles.scss

Issue #464 needed tooltips to be attached to icons.

Pbi eui qa

---

projects/ccf-eui/src/app/modules/filters/filters-content/filters-content.component.html
projects/ccf-eui/src/app/modules/filters/filters-content/filters-content.component.scss
projects/ccf-eui/src/app/shared/components/checkbox/checkbox.component.html
projects/ccf-eui/src/app/shared/components/checkbox/checkbox.component.scss
projects/ccf-eui/src/app/shared/components/checkbox/checkbox.component.ts

Add technology filters

---

projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.html
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.scss
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.html
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts

Add data counts to partonomy and organ carousel

---

projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/app.component.scss
projects/ccf-shared/src/lib/components/body-ui/body-ui.component.scss

Target issue #544 
Some of the CSS. classes were missing in the EUI which is why it was acting that way

Fix body UI regressions

---

projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.scss
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts

Carousel width isn't responsive yet but it shows all organs
#557

Fix carousel width and scroll step

---

projects/ccf-rui/src/assets/docs/README.md

I added a link to the RUI SOP to the About Md file.

Markdown updates

---

projects/ccf-rui/src/app/app.component.html
projects/ccf-rui/src/app/app.component.scss
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.scss
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.scss
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.theme.scss
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.component.scss
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.component.theme.scss
projects/ccf-rui/src/app/shared/components/name-input/name-input.component.html
projects/ccf-rui/src/app/shared/components/name-input/name-input.component.scss
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.scss
projects/ccf-rui/src/app/shared/components/rotation-slider/rotation-slider.component.theme.scss
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.scss
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.theme.scss
projects/ccf-rui/src/app/shared/components/tag-search/tag-search.component.html
projects/ccf-rui/src/app/shared/components/tag-search/tag-search.component.scss
projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.scss
projects/ccf-rui/src/themes/_light.scss
projects/ccf-shared/src/lib/components/info/info-dialog/info-dialog.component.html
projects/ccf-shared/src/lib/components/info/info-dialog/info-dialog.component.scss
projects/ccf-shared/src/lib/components/info/info-dialog/info-dialog.component.theme.scss
projects/ccf-shared/src/lib/components/opacity-slider/opacity-slider.component.scss

Pbi 568 rui fixes

---

projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/app.component.scss
projects/ccf-eui/src/app/app.component.theme.scss
projects/ccf-eui/src/app/modules/filters/filters-content/filters-content.component.scss
projects/ccf-eui/src/app/modules/filters/filters-popover/filters-popover.component.scss
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.html
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.scss
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.spec.ts
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.theme.scss
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.ts
projects/ccf-eui/src/app/modules/results-browser/donor-card/donor-card.component.scss
projects/ccf-eui/src/app/modules/results-browser/results-browser/results-browser.component.theme.scss
projects/ccf-eui/src/app/shared/components/drawer/toggle-button/toggle-button.component.scss
projects/ccf-shared/src/lib/components/body-ui/body-ui.component.scss
projects/ccf-shared/src/lib/components/info/info-button/info-button.component.scss
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.scss

#569 
- Added transition for filter popup close
- Fixed alignment of organ carousel text
- Added scroll gradient to ontology
- Removed black bar around top drawer tab
- Updated drawer refresh icon tooltip
- Inactive results now have a hover state

Pbi 569 eui updates

---

projects/ccf-eui/src/app/modules/results-browser/donor-card/donor-card.component.html
projects/ccf-eui/src/app/modules/results-browser/donor-card/donor-card.module.ts
projects/ccf-eui/src/app/modules/results-browser/tissue-section-vis/tissue-section-vis.component.html
projects/ccf-eui/src/app/modules/results-browser/tissue-section-vis/tissue-section-vis.component.scss
projects/ccf-eui/src/app/modules/results-browser/tissue-section-vis/tissue-section-vis.component.spec.ts
projects/ccf-eui/src/app/modules/results-browser/tissue-section-vis/tissue-section-vis.component.ts
projects/ccf-eui/src/app/modules/results-browser/tissue-section-vis/tissue-section-vis.module.ts
projects/ccf-eui/src/app/modules/results-browser/tissue-section-vis/tissue-section-vis.theme.scss
projects/ccf-eui/src/themes/_light.scss
projects/ccf-eui/src/themes/common/_theming.scss

needs testing and feedback from Leonard.

Pbi 466 donor cards

---

projects/ccf-body-ui/src/lib/body-ui.ts
projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/app.component.spec.ts
projects/ccf-eui/src/app/app.component.ts
projects/ccf-eui/src/app/modules/results-browser/results-browser/results-browser.component.spec.ts
projects/ccf-eui/src/themes/_light.scss
projects/ccf-rui/src/app/app.component.ts
projects/ccf-rui/src/app/modules/content/stage-nav/stage-nav.component.spec.ts
projects/ccf-rui/src/app/modules/registration-modal/registration-content/registration-content.component.spec.ts
projects/ccf-rui/src/app/modules/registration-modal/registration-modal/registration-modal.component.spec.ts
projects/ccf-rui/src/app/modules/review/review-button/review-button.component.spec.ts
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
projects/ccf-rui/src/app/shared/components/json-file-reader/json-file-reader.component.spec.ts
projects/ccf-shared/src/lib/components/body-ui/body-ui.component.spec.ts
projects/ccf-shared/src/lib/components/body-ui/body-ui.component.ts
projects/ccf-shared/src/lib/components/opacity-slider/opacity-slider.component.spec.ts
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.html
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.spec.ts
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts

- Updated demo video links.
- Organ carousel will respond to container width and show only full icons.
- EUI: clicking refresh and selecting body on partonomy resets the body view.

Pbi ccf UI updates

---

projects/ccf-body-ui/src/lib/body-ui.ts
projects/ccf-rui/src/app/modules/content/content.component.html
projects/ccf-shared/src/lib/components/body-ui/body-ui.component.ts

Pbi 416 orthographic camera

---

projects/ccf-body-ui/src/lib/body-ui.ts
projects/ccf-rui/src/app/modules/content/content.component.html
projects/ccf-shared/src/lib/components/body-ui/body-ui.component.ts

Add x rotation to gizmo

---

projects/ccf-rui/src/app/core/services/config/config.ts
projects/ccf-rui/src/app/core/store/page/page.state.spec.ts
projects/ccf-rui/src/app/core/store/page/page.state.ts
projects/ccf-rui/src/app/core/store/registration/registration.state.spec.ts
projects/ccf-rui/src/app/modules/header/header.component.html
projects/ccf-rui/src/index.html

Use cancelRegistration callback instead of homeUrl

---

projects/ccf-shared/src/lib/analytics/tracking.state.ts
projects/ccf-shared/src/lib/components/tracking-popup/tracking-popup.component.html
projects/ccf-shared/src/lib/components/tracking-popup/tracking-popup.component.ts

Refactoring dialog logic to fix reload bug

---

projects/ccf-database/src/lib/hubmap/hubmap-data-import.ts
projects/ccf-database/src/lib/hubmap/hubmap-data.ts

Replace deprecated field names

---

projects/ccf-rui/src/app/app.component.ts
projects/ccf-rui/src/app/core/services/config/config.ts
projects/ccf-rui/src/app/core/store/page/page.state.spec.ts
projects/ccf-rui/src/app/core/store/page/page.state.ts
projects/ccf-rui/src/app/core/store/registration/registration.state.spec.ts
projects/ccf-rui/src/app/core/store/registration/registration.state.ts
projects/ccf-rui/src/app/modules/content/content.component.html
projects/ccf-rui/src/app/modules/content/content.component.scss
projects/ccf-rui/src/app/modules/content/content.component.spec.ts
projects/ccf-rui/src/app/modules/header/header.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.html
projects/ccf-rui/src/app/modules/left-sidebar/left-sidebar.component.spec.ts
projects/ccf-rui/src/app/modules/registration-modal/registration-content/registration-content.component.spec.ts
projects/ccf-rui/src/app/modules/registration-modal/registration-modal/registration-modal.component.spec.ts
projects/ccf-rui/src/app/modules/registration-modal/registration-modal/registration-modal.component.ts
projects/ccf-rui/src/app/modules/review/review-button/review-button.component.html
projects/ccf-rui/src/app/modules/review/review-button/review-button.component.ts
projects/ccf-rui/src/app/modules/review/review-modal/review-modal.component.html
projects/ccf-rui/src/app/modules/review/review-modal/review-modal.component.spec.ts
projects/ccf-rui/src/app/modules/review/review-modal/review-modal.component.ts
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
projects/ccf-rui/src/index.html

Remove references to embedded and tutorial mode

---

projects/ccf-eui/src/app/app.component.ts
projects/ccf-eui/src/app/core/services/theming/theming.service.ts

Set theme according to user preference

---

EMBEDDING.md
projects/ccf-database/src/lib/ccf-database.ts
projects/ccf-rui/src/webcomponent-example.html

first draft, let me know any changes wanted.

updating markdown file

---

package-lock.json
projects/ccf-database/src/lib/hubmap/hubmap-data.ts
projects/ccf-eui/src/app/app.component.scss
projects/ccf-eui/src/app/app.component.theme.scss
projects/ccf-eui/src/app/shared/components/thumbnail-carousel/thumbnail-carousel.component.scss

Pbi 624 dataset thumbnails

---

projects/ccf-organ-info/src/app/app.module.ts
projects/ccf-organ-info/src/app/modules/link-cards/link-cards.component.html
projects/ccf-organ-info/src/app/modules/link-cards/link-cards.module.ts
projects/ccf-organ-info/src/environments/environment.prod.ts
projects/ccf-organ-info/src/environments/environment.staging.ts
projects/ccf-organ-info/src/environments/environment.ts
projects/ccf-shared/analytics/package.json
projects/ccf-shared/analytics/src/lib/analytics.module.ts
projects/ccf-shared/analytics/src/public-api.ts
tsconfig.json

- Created new entry point in ccf-shared for analytics code (old code in main folder should be migrated to new location in the future \w necessary updates [[needs to handle when app is used as a web component]])
- Added google analytics without consent popup

Pbi 667 google analytics

---

projects/ccf-organ-info/src/app/app.component.html
projects/ccf-organ-info/src/app/app.component.scss
projects/ccf-organ-info/src/app/app.component.ts
projects/ccf-organ-info/src/app/features/organ/organ.component.scss
projects/ccf-organ-info/src/app/modules/stats-list/stats-list.component.scss
projects/ccf-organ-info/src/styles.scss

Fix resizing of the organ component

Pbi styling fixes

---

projects/ccf-rui/src/app/shared/components/visibility-menu/visibility-menu.component.html
projects/ccf-rui/src/assets/reference-organ-data.json
projects/ccf-shared/src/lib/components/opacity-slider/opacity-slider.component.scss

#527
#654 
Styling changes to prevent scrollbars from showing up when not needed

Fix unnecessary scrollbars; change opacity slider popup behavior; remove HuBMAP colon extraction sites

---

projects/ccf-eui/src/app/app.component.spec.ts
projects/ccf-eui/src/app/app.component.ts
projects/ccf-eui/src/app/core/core.module.ts
projects/ccf-eui/src/app/core/store/store.module.ts
projects/ccf-rui/src/app/app.component.ts
projects/ccf-rui/src/app/core/core.module.ts
projects/ccf-rui/src/app/core/store/store.module.ts
projects/ccf-shared/analytics/src/lib/analytics.module.ts
projects/ccf-shared/analytics/src/lib/consent.service.ts
projects/ccf-shared/analytics/src/lib/google-analytics-sync.service.ts
projects/ccf-shared/analytics/src/lib/local-storage-sync.service.ts
projects/ccf-shared/analytics/src/public-api.ts
projects/ccf-shared/src/lib/components/tracking-popup/tracking-popup.component.html
projects/ccf-shared/src/lib/components/tracking-popup/tracking-popup.component.spec.ts
projects/ccf-shared/src/lib/components/tracking-popup/tracking-popup.component.ts

Pbi 701 refactor google analytics

---

projects/ccf-body-ui/src/lib/util/process-scene-nodes.ts
projects/ccf-eui/src/app/core/store/scene/scene.state.ts
projects/ccf-organ-info/src/app/features/organ/organ.component.html
projects/ccf-organ-info/src/app/features/organ/organ.component.ts

Clicking a block now highlights it

---

projects/ccf-eui/src/app/app-web-component.component.ts
projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/app.component.spec.ts
projects/ccf-eui/src/app/app.component.ts
projects/ccf-eui/src/app/app.module.ts
projects/ccf-organ-info/src/app/app-web-component.component.ts
projects/ccf-organ-info/src/app/app.component.html
projects/ccf-organ-info/src/app/app.component.ts
projects/ccf-organ-info/src/app/app.module.ts
projects/ccf-organ-info/src/app/core/store/store.module.ts
projects/ccf-rui/src/app/app-web-component.component.ts
projects/ccf-rui/src/app/app.module.ts
projects/ccf-shared/web-components/package.json
projects/ccf-shared/web-components/src/lib/config-manager.ts
projects/ccf-shared/web-components/src/lib/parsers.ts
projects/ccf-shared/web-components/src/lib/web-component.ts
projects/ccf-shared/web-components/src/public-api.ts
tsconfig.json

Improved the way the apps works as web components

Web component improvements

---

projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.scss

Increase max-height of AS-tag area

---

projects/ccf-eui/src/themes/_dark.scss

Pbi 715 z axis fix

---

projects/ccf-database/src/lib/interfaces.ts
projects/ccf-organ-info/src/app/app-web-component.component.ts
projects/ccf-organ-info/src/app/app.component.html
projects/ccf-organ-info/src/app/app.component.scss
projects/ccf-organ-info/src/app/app.component.ts
projects/ccf-organ-info/src/app/core/services/organ-lookup/organ-lookup.service.ts
projects/ccf-organ-info/src/app/features/organ/organ.component.ts
projects/ccf-organ-info/src/index.html
projects/ccf-organ-info/src/styles.scss

Pbi 694 block highlight

---

projects/ccf-database/src/lib/hubmap/hubmap-data-import.ts

- Limit what fields are returned in a search
- Limit the number of items per request to fit in aprox. 10Mb

Split api searches into multiple request

---

projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html

Restarted updating RUI tutorial YT link from `main` branch.

Updated YT link for RUI v3.0.0 tutorial

---

projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.html
projects/ccf-rui/src/assets/docs/README.md

@bherr2 
Changed "tissue slice" to "tissue section" to unify language across RUI, SOP, and CCF UI paper.

Updated "tissue slice" to "tissue "section"

---

projects/ccf-organ-info/src/app/app.component.ts
projects/ccf-organ-info/src/app/core/services/organ-lookup/organ-lookup.service.ts
projects/ccf-organ-info/src/app/features/organ/organ.component.html
projects/ccf-organ-info/src/app/features/organ/organ.component.ts
projects/ccf-organ-info/src/environments/environment.prod.ts
projects/ccf-organ-info/src/environments/environment.staging.ts
projects/ccf-organ-info/src/environments/environment.ts
projects/ccf-organ-info/src/index.html
projects/ccf-shared/src/lib/components/body-ui/body-ui.component.ts
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts

Fixes to make the organ-info wc more reliable and work with all 3.0 Reference Organs

organ-info improvements

---

projects/ccf-rui/src/app/core/store/model/model.state.ts
projects/ccf-shared/src/lib/components/organ-selector/organ-selector.component.ts

Add logging to organ and block position

---

.env.example
ccf-api-spec.yaml
projects/ccf-api/src/lib/routes/v1/gtex/index.ts
projects/ccf-api/src/lib/routes/v1/gtex/rui-locations.ts
projects/ccf-api/src/lib/routes/v1/index.ts

Use GTEx API to update rui_locations.jsonld

---

projects/ccf-eui/src/assets/gtex/data/rui_locations.jsonld

Removed duplicate skin tissue block
Added back missing VHF small intestine tissue block

Fix error with skin/small intestine tissue block count for GTEx

---

projects/ccf-eui/src/app/core/header/header.component.scss
projects/ccf-eui/src/assets/icons/app/default-logo.svg
projects/ccf-eui/src/styles.scss
projects/ccf-rui/src/styles.scss

Adjust logo styling

---

ccf-api-spec.yaml
projects/ccf-api/src/lib/routes/v1/get-spatial-placement.ts
projects/ccf-api/src/lib/routes/v1/index.ts
projects/ccf-database/package.json
projects/ccf-database/src/lib/ccf-database.ts
projects/ccf-database/src/lib/ccf-spatial-graph.ts
projects/ccf-database/src/lib/spatial-types.ts

for a rui location and a given target space

Added route for getting a spatial placement 

---

projects/ccf-eui/src/app/app.component.html
projects/ccf-eui/src/app/app.component.scss
projects/ccf-eui/src/app/app.component.ts
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.scss

Fix scrollbar on Firefox

---

projects/ccf-eui/src/app/modules/filters/filters-content/filters-content.component.html
projects/ccf-eui/src/app/modules/filters/filters-content/filters-content.component.scss
projects/ccf-eui/src/app/modules/filters/filters-popover/filters-popover.component.scss
projects/ccf-eui/src/app/shared/components/checkbox/checkbox.component.scss
projects/ccf-eui/src/app/shared/components/dropdown/dropdown.component.html
projects/ccf-eui/src/app/shared/components/dropdown/dropdown.component.scss
projects/ccf-eui/src/index.html
projects/ccf-eui/src/styles.scss

Filters popup styling improvements

---

projects/ccf-eui/src/app/app.component.scss
projects/ccf-eui/src/app/modules/filters/filters-popover/filters-popover.component.scss
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-selection/ontology-selection.component.spec.ts
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.spec.ts
projects/ccf-eui/src/app/modules/ontology-exploration/ontology-tree/ontology-tree.component.ts
projects/ccf-eui/src/app/shared/components/drawer/drawer/drawer.component.scss
projects/ccf-eui/src/app/shared/components/viewer/viewer.component.scss
projects/ccf-shared/src/lib/components/spatial-search-list/spatial-search-list.component.scss

Eui styling modifications

---

projects/ccf-rui/src/app/app.component.html
projects/ccf-rui/src/app/app.component.ts
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.html
projects/ccf-rui/src/app/modules/right-sidebar/right-sidebar.component.ts
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.component.html
projects/ccf-rui/src/app/shared/components/block-size-input/block-size-input.component.theme.scss
projects/ccf-rui/src/app/shared/components/name-input/name-input.component.html
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.html
projects/ccf-rui/src/app/shared/components/slices-input/slices-input.component.theme.scss

Enable keyboard shortcuts when registration hidden
